services:
  cardealership:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: adopter-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql1:
        condition: service_healthy

  mysql1:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=adopter-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql-adopter:/var/lib/mysql
      - ./adopter-service/data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin-adopter:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin-adopter
    links:
      - mysql1:db
    restart: always
    ports:
      - 5014:80
    environment:
      - PMA_ARBITRARY=1