version: '3.8'

services:

  # MongoDB container
  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
    volumes:
      - mongo_data:/data/db

  # Optional: Mongo Express GUI for viewing data in browser
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_MONGODB_SERVER: mongodb  # must match Mongo service name
    depends_on:
      - mongodb

volumes:
  mongo_data:
